# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170531_0206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='WebUser',
        ),
    ]
