# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170531_0255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebUser',
        ),
    ]
